/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    Updater: () => import('#controllers/api/updater_controller'),
  },
  cms: {
    Artifacts: () => import('#controllers/cms/artifacts_controller'),
    Dashboards: () => import('#controllers/cms/dashboards_controller'),
    Profiles: () => import('#controllers/cms/profiles_controller'),
    Settings: () => import('#controllers/cms/settings_controller'),
    StorageProviders: () => import('#controllers/cms/storage_providers_controller'),
    Users: () => import('#controllers/cms/users_controller'),
    Versions: () => import('#controllers/cms/versions_controller'),
  },
  Session: () => import('#controllers/session_controller'),
}
