/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArchitectureSchema extends BaseModel {
  static $columns = ['deletedAt', 'displayName', 'id', 'name'] as const
  $columns = ArchitectureSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
}

export class ArtifactSchema extends BaseModel {
  static $columns = ['architectureId', 'channel', 'checksum', 'checksumMd5', 'checksumSha1', 'checksumSha256', 'checksumSha512', 'createdAt', 'deletedAt', 'downloadCount', 'fileName', 'id', 'isArchived', 'isPublished', 'mimeType', 'platformId', 'publishedAt', 'sizeBytes', 'storageKey', 'storageProviderId', 'versionId'] as const
  $columns = ArtifactSchema.$columns
  @column()
  declare architectureId: string
  @column()
  declare channel: string
  @column()
  declare checksum: string | null
  @column()
  declare checksumMd5: string | null
  @column()
  declare checksumSha1: string | null
  @column()
  declare checksumSha256: string | null
  @column()
  declare checksumSha512: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare downloadCount: number
  @column()
  declare fileName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isArchived: boolean
  @column()
  declare isPublished: boolean
  @column()
  declare mimeType: string | null
  @column()
  declare platformId: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare sizeBytes: bigint | number | null
  @column()
  declare storageKey: string
  @column()
  declare storageProviderId: string
  @column()
  declare versionId: string
}

export class DownloadHistorySchema extends BaseModel {
  static $columns = ['artifactId', 'countryCode', 'createdAt', 'deletedAt', 'id', 'ipAddress', 'lat', 'lng', 'userAgent'] as const
  $columns = DownloadHistorySchema.$columns
  @column()
  declare artifactId: string
  @column()
  declare countryCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare lat: number | null
  @column()
  declare lng: number | null
  @column()
  declare userAgent: string | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'expiresAt', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class PlatformSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'displayName', 'id', 'name', 'updatedAt'] as const
  $columns = PlatformSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'key', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class StorageProviderSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'deletedAt', 'id', 'isActive', 'isDefault', 'name', 'quotaBytes', 'type'] as const
  $columns = StorageProviderSchema.$columns
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare quotaBytes: bigint | number | null
  @column()
  declare type: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'fullName', 'id', 'isRoot', 'passwordHash', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isRoot: boolean
  @column()
  declare passwordHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VersionSchema extends BaseModel {
  static $columns = ['changelog', 'codename', 'createdAt', 'deletedAt', 'id', 'isActive', 'major', 'minor', 'patch', 'releaseDate'] as const
  $columns = VersionSchema.$columns
  @column()
  declare changelog: string | null
  @column()
  declare codename: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare major: number
  @column()
  declare minor: number
  @column()
  declare patch: number
  @column.dateTime()
  declare releaseDate: DateTime | null
}
